name: integra_espoir
description: A new Flutter project.
publish_to: 'none'
version: 1.3.0+13

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  badges: ^3.1.2
  connectivity_plus: ^4.0.2
  device_info_plus: ^8.2.2
  dio: ^5.1.2
  dropdown_search: ^5.0.6
  fl_animated_linechart: ^1.1.9
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_secure_storage: ^8.0.0
  font_awesome_flutter: ^10.4.0
  formz: ^0.6.0
  geolocator: ^10.1.0
  go_router: ^6.5.8
  google_maps_flutter: ^2.5.3
  image_picker: ^1.0.7
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  loading_animation_widget: ^1.2.1
  path_provider: ^2.1.1
  permission_handler: ^11.2.0
  platform_device_id: ^1.0.1
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.6
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icono/icono_mobil.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/ca/
